import type { Metadata } from "next";
import { Poppins as FontSans } from "next/font/google";
import "@/app/styles/globals.css";

const fontSans = FontSans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-sans",
});
export const metadata: Metadata = {
  title: "Abdullah Shakur | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Google tag (gtag.js) */}
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-P58FPZ20R8"></script>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-P58FPZ20R8');
            `,
          }}
        />
      </head>
      <body className={fontSans.variable}>{children}
      <!-- Start of Waypoint Converts Navigator Config Code -->
<script>
    window.acNavigatorConfig = {
        id: '57f32fb1-acc3-4c3d-80f1-f502d13bd357',
        host: 'https://local.waypointconverts.com:8081'
    }
</script>
<script>(function(){var c=window.acNavigatorConfig;var d=document;var s=d.createElement('script');s.type='text/javascript';s.async=true;s.src=c.host+'/navigator/launcher/js/'+c.id;(d.body||d.head).appendChild(s)})()</script>
      </body>
    </html>
  );
}
