import type { Metadata } from "next";
import { Poppins as FontSans } from "next/font/google";
import "@/app/styles/globals.css";

const fontSans = FontSans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-sans",
});
export const metadata: Metadata = {
  title: "Abdullah Shakur | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-KNKTG93V');</script>
        {/* Google tag (gtag.js) */}
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-P58FPZ20R8"></script>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-P58FPZ20R8');
            `,
          }}
        />
      </head>
      <body className={fontSans.variable}>
        {children}
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-KNKTG93V"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
        {/* Start of Waypoint Converts Navigator Config Code */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              window.acNavigatorConfig = {
                  id: '57f32fb1-acc3-4c3d-80f1-f502d13bd357',
                  host: 'https://local.waypointconverts.com:8081'
              }
            `,
          }}
        />
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function(){var c=window.acNavigatorConfig;var d=document;var s=d.createElement('script');s.type='text/javascript';s.async=true;s.src=c.host+'/navigator/launcher/js/'+c.id;(d.body||d.head).appendChild(s)})()
            `,
          }}
        />
      </body>
    </html>
  );
}
